<?php

/**
*Implements hook_menu
*/
function icer_main_menu() {

  $items['custom_front'] = array(
    'title' => t('Home Page'),
    'page callback' => 'icer_main_home_page_callback',
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
    'options' => array('attributes' => array('class' => array('menu__item', 'frontpage'))),
  );

  $items['user/account/%'] = array(
    'title' => t('Edit User Acount'),
    'page callback' => 'icer_main_account_callback',
    'access callback' => TRUE,
    'page arguments' => array(2),
    'options' => array('attributes' => array('class' => array('menu__item', 'edit-user'))),
  );

  return $items;
}

function icer_main_home_page_callback(){
  return 'home';
}

function icer_main_account_callback($uid_from_url){

  global $user;
  $uid = $user->uid;  

  if ($uid == $uid_from_url):
    $block = module_invoke('views', 'block_view', 'account-block');
    return render($block['content']);
  else:
    drupal_not_found();
  endif; 

}



/**
* Implements hook_form_FORM_ID_alter
**/

function icer_main_form_user_login_block_alter(&$form, &$form_state, $form_id) {
  // Modification for the form with the given form ID goes here. For example, if
  // FORM_ID is "user_register_form" this code would run only on the user
  // registration form.

  // Add a checkbox to registration form about agreeing to terms of use.
  dpm($form);
  //$form['links']['#markup'] = '';
}

/**
* Implements custom blocks
**/

function icer_main_block_info() {

  $blocks['user_button_top'] = array(
    'info' => t('User buttons on top site'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

function icer_main_block_view($delta = '') {

  $block = array();

  $link = '#';

  switch ($delta) {
  case 'user_button_top':
    $block['subject'] = t('User Top Buttons');
    if (user_is_logged_in()):
      global $user;
      $uid = $user->uid;
      $block['content'] = array(
        '#theme' => 'user_button_top_theme',
        '#flag_display_item' => TRUE,
        '#user_login_link' => $GLOBALS['base_path']. 'user/logout',
        '#profil_link' => $GLOBALS['base_path']. 'user/account/'.$uid,
        '#message_link' => $link,
        '#checkout_link' => $link,
        '#add_skils_link' => $link,        
      );
    else:
      $block['content'] = array(
        '#flag_display_item' => FALSE,
        '#theme' => 'user_button_top_theme',
        '#user_login_image' => 'fa-power-off',
        '#user_login_link' => $GLOBALS['base_path']. 'user',        
      );
    endif;  
  break;

  };

  return $block;

} 

function icer_main_theme() {

  $themes = array();

  $themes['user_button_top_theme'] = array(
    'variables' => array(
      'user_login_link' => NULL,
      'profil_link' => NULL,
      'message_link' => NULL,
      'checkout_link' => NULL,
      'add_skils_link' => NULL,
      'flag_display_item' => NULL,
    ),

    'template' => 'user_button_top',
  );

  return $themes;
}   